### ISSUE TITLE
ZDEMO_EXCEL3 and ZDEMO_EXCEL50

### ISSUE THREAD

**Issue by StoneRanger** [abap2xlsx/demos#12]
Should we expect drop downs in Excel for the Airline column after executing ZDEMO_EXCEL3 and ZDEMO_EXCEL50.

I think we need to modify the ZDEMO_EXCEL3 with as from line 108

  lo_data_validation->cell_row    = 1.   " Was 4
  lo_data_validation->cell_column = 'A'. " Was C
  lo_data_validation->cell_row_to    = 9.   " Added
  lo_data_validation->cell_column_to = 'A'. " Added

Then we have dropdowns as shown in DDL1

As ZDEMO_EXCEL50 is using the Huge File writer is this also possible to have DataValidations with this Writer?

Greetings,

![DDL1](https://user-images.githubusercontent.com/5841009/179731192-088454b8-23f3-4d9d-872e-512d67ed4189.JPG)
?

**Comment by AndreaBorgia-Abo** [comment]
While reviewing #16 , I noticed that ZDEMO_EXCEL_CHECKER reported differences on ZDEMO_EXCEL3 and ZDEMO_EXCEL15_03, which should be investigated, either fixing the cause or updating the reference file. This happened with both versions of the checker, so it's not a new issue with the checker itself.

**Comment by AndreaBorgia-Abo** [comment]
Old: `<pane ySplit="3" topLeftCell="A4" activePane="bottomRight" state="frozen"/>`
New: `<pane ySplit="3" xSplit="1" topLeftCell="B4" activePane="bottomRight" state="frozen"/>`

**Comment by AndreaBorgia-Abo** [comment]
Sorry for the noise: I had originally added here the comments on a possibly regression but I have since moved them to a [new issue](https://github.com/abap2xlsx/demos/issues/19). Please keep this in mind. Thanks.

**Comment by AndreaBorgia-Abo** [comment]
#41 should deal with ZDEMO_EXCEL3 and the issue could be closed.
Suggest opening a new issue with respect to the enhancement of the huge writer class, if needed.

**Comment by sandraros** [comment]
Thanks @AndreaBorgia-Abo. Fix merged. Sorry for the late review.
I agree concerning the enhancement of the huge writer class.
