### ISSUE TITLE
sync release tags with main library

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2xlsx/demos#17]
After splitting the demos from the library, we probably need a way to inform users about the appropriate version of the demos for each release.
I propose tagging this repo with release tags (es. v7.16.0), corresponding to the latest commit before the tagging in main library. We could probably do this now only for 7.16.0 but in the future it should probably be noted in the release checklist and in the Readme.

**Comment by sandraros** [comment]
Agreed!

**Comment by AndreaBorgia-Abo** [comment]
Ok, other than an extra (unwanted) dot after the "v" it's done.
