### ISSUE TITLE
possible regression in ZDEMO_EXCEL36 or outdated reference file

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2xlsx/demos#18]
While reviewing #16 , I noticed that ZDEMO_EXCEL_CHECKER reported differences on ZDEMO_EXCEL36, which should be investigated, either fixing the cause or updating the reference file. This happened with both versions of the checker, so it's not a new issue with the checker itself.

**Comment by AndreaBorgia-Abo** [comment]
Difference report:
* new_sheet3.xml_worksheets_xl.xml : multiple cells have a  Style Index value (see 18.3.1.4 in "Ecma Office Open XML Part 1 - Fundamentals And Markup Language Reference.pdf") of 3 in the reference file and 2 in the generated file
* new_sheet2.xml_worksheets_xl.xml : same as above
* no other changes

**Comment by AndreaBorgia-Abo** [comment]
c6e5ad6ee63429c4ee16ba796738c7ee46c9a3d0 is the first bad commit

**Comment by sandraros** [comment]
Thanks. Agreed!
