### ISSUE TITLE
ZDEMO_EXCEL_COMMENTS missing one line of code to add comment

### ISSUE THREAD

**Issue by jpbourne** [abap2xlsx/demos#33]
The following line of code is missing in program **ZDEMO_EXCEL_COMMENTS**:

```abap
  CONCATENATE 'A comment split' cl_abap_char_utilities=>cr_lf 'on 2 lines?' INTO lv_comment.
  lo_comment->set_text( ip_ref = 'F6' ip_text = lv_comment ).
****** The following line must be added: ******
  lo_worksheet->add_comment( lo_comment ).

  " Second sheet
  lo_worksheet = lo_excel->add_new_worksheet( ).
```
I would be happy to submit a pull request for this change if I had permissions.

**Comment by larshp** [comment]
just do a fork, see https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by jpbourne** [comment]
Thanks @larshp I am still learning the GitHub workflow, your help is much appreciated. [Pull request](https://github.com/abap2xlsx/demos/pull/34) created.
